# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: (Apache-2.0 OR BSD-3-Clause)
version: 2.1

jobs:
  application:
    docker:
      - image: digitalasset/daml-sdk:1.2.0
        user: root
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2
      - run:
          name: Build Application
          command: |
            apk add make maven
            su - daml -s /bin/bash
            make build-app
      - run:
          name: Test Application
          command: make test-app
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
      - run:
          name: Save test results
          command: |
            mkdir -pv ~/test-results/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  daml:
    docker:
      - image: digitalasset/daml-sdk:1.2.0
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Dar
          command: |
            apk add make maven
            su - daml -s /bin/bash -c "make test-dar"
      - run:
          name: Build Dar
          command:  |
            su - daml -s /bin/bash -c "make build-dar"
      - run:
          name: Save test results
          command: |
            su - daml -s /bin/bash -c "mkdir -pv ~/test-results/daml"
            su - daml -s ibin/bash -c "find . -type f -regex ".*/target/.*DarTests.xml" -exec cp {} ~/test-results/daml/ \;"
      - store_test_results:
          path: ~/test-results
  integration-test:
    docker:
      - image: digitalasset/daml-sdk:1.2.0
    steps:
      - checkout
      - run:
          name: Test all the things.
          command: echo '[STUB] test some things'
      - run:
          name: Save test results
          command: mkdir -pv ~/test-results/integration
      - store_test_results:
          path: ~/test-results

workflows:
  Build and test:
    jobs:
      - application
      - daml
      - integration-test:
          requires:
            - application
            - daml
