#!/usr/bin/env bash

# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail


BASE=$(dirname $0)/..
VERSION=1.0

cd $BASE
daml start --open-browser no --on-start "scripts/startApp" --wait-for-signal no
